Add -f to svn-push

diff --git a/bin/svn-push b/bin/svn-push
--- a/bin/svn-push
+++ b/bin/svn-push
@@ -7,13 +7,23 @@ set -e
 
 cd $(dirname $0)/..
 
-if [ -n "$(git status -s -uno)" ]; then
-	git status
-	echo "Error: Git state has modified or staged files. Commit or reset." >&2
-	exit 1
-fi
 if [ ! -e svn-url ]; then
 	echo "Error: Missing svn-url file" >&2
+	exit 1
+fi
+
+force=
+while getopts 'f' option; do
+	case $option in
+		f)
+			force=1
+			;;
+	esac
+done
+
+if [ -n "$(git status -s -uno)" ] && [ -z "$force" ]; then
+	git status
+	echo "Error: Git state has modified or staged files. Commit or reset, or supply -f" >&2
 	exit 1
 fi
 
@@ -52,8 +62,8 @@ if ! grep -q "$plugin_version" readme.txt; then
 	exit 1
 fi
 
-if git show-ref --tags --quiet --verify -- "refs/tags/$plugin_version"; then
-	echo "Plugin version $plugin_version already tagged. Please bump version and try again"
+if git show-ref --tags --quiet --verify -- "refs/tags/$plugin_version" && [ -z "$force" ]; then
+	echo "Plugin version $plugin_version already tagged. Please bump version and try again, or supply -f"
 	exit 1
 fi
 
